version: '3'
services:
  oq-braket:
    container_name: oq-aws-jobs-local
    build: .
  qvm:
    container_name: qvm
    image: rigetti/qvm:latest
  quilc:
    container_name: quilc
    image: rigetti/quilc:latest 

